#!/usr/bin/env zsh

root_dir="$1/"
temp_dir="${root_dir}temp/"
transactions="${root_dir}transactions.csv"
budget="${root_dir}budget.csv"
earnings="${root_dir}earnings.csv"
transactions_all="${root_dir}transactions_all.csv"
monthly="${root_dir}month-biweek.csv"
monthly_temp="${root_dir}month-biweek_temp.csv"
temp="${root_dir}temp.csv"
md_table="${root_dir}month-biweek.md"

mkdir $temp_dir
bat $transactions | sd "\n" ",spending\n" | sd "(amount,)\w+" "\${1}type" >"${temp_dir}transactions.csv"
bat $budget | sd "\n" ",budget\n" | sd "(amount,)\w+" "\${1}type" >"${temp_dir}budget.csv"
bat $earnings | sd "\n" ",earning\n" | sd "(amount,)\w+" "\${1}type" >"${temp_dir}/earnings.csv"

rm $md_table $monthly $transactions_all

if command -v qsv &>/dev/null; then
    all_transactions=$(qsv cat rows "${temp_dir}transactions.csv" "${temp_dir}earnings.csv" "${temp_dir}budget.csv")
else
    all_transactions=$(qsvlite cat rows "${temp_dir}transactions.csv" "${temp_dir}earnings.csv" "${temp_dir}budget.csv")
fi

echo $all_transactions | csvq -g -o $transactions_all -s join-transactions.sql

bat $transactions_all | csvq -g -o $monthly_temp -s month-biweek.sql

bat $monthly_temp | csvq -g -o $temp -s month.sql

if command -v qsv &>/dev/null; then
    qsv cat rows $monthly_temp $temp -o $monthly
else
    qsvlite cat rows $monthly_temp $temp -o $monthly
fi

pandoc -f csv -t gfm $monthly -o $md_table
rm $monthly_temp $temp
rm -rf $temp_dir
bat $md_table
